version = 1
SPDX-PackageName = ".github"
SPDX-PackageDownloadLocation = "https://github.com/cloudoperators/.github"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and Greenhouse contributors and portal contributors."
SPDX-License-Identifier = "Apache-2.0"
